### ISSUE TITLE
Difference between packages?

### ISSUE THREAD

**Issue by hailwood** [thisisbd/silverstripe-fontawesome-iconpickerfield#3]
Just wondering if there is any difference between your package and https://github.com/peavers/silverstripe-font-awesome?

If not it may be a decent idea to merge them so we don't have multiple packages for the same purpose?

Regards,

**Comment by dljoseph** [comment]
Not sure if there are differences.  All I know is that I write my module first and then Chris Turner decided to adapt the same concept...at least he admits that much in the history of his readme file here: https://github.com/peavers/silverstripe-font-awesome/commit/8119bc274fc445dfefbeadd0bf48886c1113e05d  
Not sure why Chris Turner (peavers) didn't submit a pull request.  I suspect he made several enhancements and decided his changes are too extensive to merge back in?
